version: '3'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:80'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
